version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    networks:
      - g2net
    volumes:
      - .:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  frontend_node_modules:

networks:
  g2net:
    external: true